// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package ehstreammeta

import "sync"

type Cache struct {
	items   map[string]*App
	itemsMu sync.Mutex
}

func NewCache() *Cache {
	return &Cache{
		items: map[string]*App{},
	}
}

func (c *Cache) Get(
	cacheKey string,
	factory func() *App,
) *App {
	if c == nil {
		return factory()
	}

	c.itemsMu.Lock()
	defer c.itemsMu.Unlock()

	item := c.items[cacheKey]

	if item == nil {
		item = factory()

		c.items[cacheKey] = item
	}

	return item
}
