name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: v0.4.1
        qemu-version: latest
    - name: Download Turbo Bob
      run: curl --fail --location --output bob https://github.com/function61/turbobob/releases/download/20200910_1241_90ec91c9/bob_linux-amd64 && chmod +x bob
    - name: Build with Turbo Bob
      run: CI_REVISION_ID="$GITHUB_SHA" ./bob build --publish-artefacts
      # unfortunately there doesn't seem to be a way to "expose all secrets", so you must
      # list here each secret to pass on to the build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENTHORIZON: ${{ secrets.EVENTHORIZON }}
